### ISSUE TITLE
Error: Command failed: node lib

### ISSUE THREAD

**Issue by guillaumeguillaume** [verekia/js-stack-from-scratch#103]
### Type of issue: (feature suggestion, bug, translation?)

Bug?

### Chapter:

7

### If it's a bug:

I just did the following command:

```We are not going to do any Node back-end yet, but this separation will help you see more clearly where things belong. You'll need to change the import Dog from './dog'; in server/index.js to import Dog from '../shared/dog'; though, or ESLint will detect errors for unresolved modules.
```

and i get the following error right away:

```
[15:25:42] Starting 'main'...

[15:25:42] 'main' errored after 61 ms
[15:25:42] Error: Command failed: node lib
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/guillaumegaluz/Projects/js_app/lib'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by guillaumeguillaume** [comment]
my gulpfile.babel.js looks like:

```
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable no-console */

import gulp from 'gulp';
import babel from 'gulp-babel';
import del from 'del';
import { exec } from 'child_process';
import eslint from 'gulp-eslint';

const paths = {
  allSrcJs: 'src/**/*.js',
  gulpFile: 'gulpfile.babel.js',
  libDir: 'lib',
};

gulp.task('clean', () => {
  return del(paths.libDir);
});

gulp.task('build', ['lint', 'clean'], () => {
  return gulp.src(paths.allSrcJs)
    .pipe(babel())
    .pipe(gulp.dest(paths.libDir));
});

gulp.task('main', ['build'], (callback) => {
  exec(`node ${paths.libDir}`, (error, stdout) => {
    console.log(stdout);
    return callback(error);
  });
});

gulp.task('watch', () => {
  gulp.watch(paths.allSrcJs, ['main']);
});

gulp.task('lint', () => {
  return gulp.src([
    paths.allSrcJs,
    paths.gulpFile,
  ])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
});

gulp.task('default', ['watch', 'main']);
```

```
$ node -v
v6.2.1
```

**Comment by guillaumeguillaume** [comment]
and `lib` does exist:

```
guillaume-C02PQ2SDFVH8:js_app guillaumegaluz$ pwd
/Users/guillaumegaluz/Projects/js_app
guillaume-C02PQ2SDFVH8:js_app guillaumegaluz$ ls -la
total 224
drwxr-xr-x   11 guillaumegaluz  staff    374 Nov 23 15:30 .
drwxr-xr-x    7 guillaumegaluz  staff    238 Nov 22 16:35 ..
-rw-r--r--@   1 guillaumegaluz  staff   6148 Nov 22 16:58 .DS_Store
-rw-r--r--    1 guillaumegaluz  staff     49 Nov 23 14:45 .gitignore
drwxr-xr-x    3 guillaumegaluz  staff    102 Nov 23 15:16 dist
-rw-r--r--    1 guillaumegaluz  staff    991 Nov 23 15:25 gulpfile.babel.js
drwxr-xr-x    5 guillaumegaluz  staff    170 Nov 23 15:30 lib
drwxr-xr-x  383 guillaumegaluz  staff  13022 Nov 23 15:00 node_modules
-rw-r--r--    1 guillaumegaluz  staff    753 Nov 23 15:14 package.json
drwxr-xr-x    5 guillaumegaluz  staff    170 Nov 23 15:18 src
-rw-r--r--    1 guillaumegaluz  staff  91167 Nov 23 15:00 yarn.lock
```

**Comment by guillaumeguillaume** [comment]
i guess we need to point to the new location of `index.js`

i fixed it with

```
exec(`node ${paths.libDir}/server`, (error, stdout) => {
```

on line 27

is that cool?

I changed `libDir: 'lib',` to `libDir: 'lib/server',` but i threw:

```
[15:38:36] 'main' errored after 58 ms
[15:38:36] Error: Command failed: node lib/server
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/guillaumegaluz/Projects/js_app/lib/server'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by verekia** [comment]
Hey :) The thing is, this chapter sets you up with a new main task later on, so it's not really relevant to run `node lib/server` at this point of the tutorial. Just go a bit further to get the Webpack part working and you'll be all set! Refer to the code provided in the repo to see how the main task changed.

**Comment by guillaumeguillaume** [comment]
Yep, that's what I realized later. I was trying to keep the server running the whole time. Things made sense at the end of the chapter, sorry I didn't update the issue. Merci!

**Comment by n-marshall** [comment]
It's true this part also got me confused and looking for a mistake that I would have made.
