### ISSUE TITLE
error when running "yarn start"

### ISSUE THREAD

**Issue by marko-mlinarevic** [verekia/js-stack-from-scratch#199]
### Type of issue: (feature suggestion, bug?)

Error

### Chapter:

04

### Error:
```
yarn start v0.20.3
$ yarn dev:start
yarn dev:start v0.20.3
$ nodemon -e js,jsx --ignore lib --ignore dist --exec babel-node src/server
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/server`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (E:\Stacks\JStack\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (E:/Stacks/JStack/src/server/index.js:24:5)
    at Module._compile (module.js:573:32)
    at loader (E:\Stacks\JStack\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Stacks\JStack\node_modules\babel-register\lib\node.js:154:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by verekia** [comment]
You likely had some ongoing server running already, maybe in an other terminal tab or from an other app. What shows up when you hit `localhost:8000`?

**Comment by marko-mlinarevic** [comment]
yup that was the issue.
