### ISSUE TITLE
Chapter 6 error

### ISSUE THREAD

**Issue by jfelipebc** [verekia/js-stack-from-scratch#23]
Hi

When I execute "yarn start" in the Chapter 6, showing this error:

```
/home/username/Proyectos/tutoriales/stack_scratch/gulpfile.babel.js:3
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/home/username/Proyectos/tutoriales/stack_scratch/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/username/Proyectos/tutoriales/stack_scratch/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/home/username/Proyectos/tutoriales/stack_scratch/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/username/Proyectos/tutoriales/stack_scratch/node_modules/liftoff/index.js:198:16) 
```

### gulpfile.babel.js ###
```
/* eslint-disable import/no-extraneous-dependencies */

import gulp from 'gulp';
import babel from 'gulp-babel';
import eslint from 'gulp-eslint';
import del from 'del';
import { exec } from 'child_process';

const paths = {
  allSrcJs: 'src/**/*.js',
  gulpFile: 'gulpfile.babel.js',
  libDir: 'lib',
};

gulp.task('lint', () =>
  gulp.src([
    paths.allSrcJs,
    paths.gulpFile,
  ])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
);

gulp.task('clean', () => del(paths.libDir));

gulp.task('build', ['lint', 'clean'], () =>
  gulp.src(paths.allSrcJs)
    .pipe(babel())
    .pipe(gulp.dest(paths.libDir))
);

gulp.task('main', ['build'], (callback) => {
  exec(`node ${paths.libDir}`, (error, stdout) => {
    console.log(stdout);
    return callback(error);
  });
});

gulp.task('watch', () => {
  gulp.watch(paths.allSrcJs, ['main']);
});

gulp.task('default', ['watch', 'main']);
```

PD: This happen in my local project
Thanks in advance

**Comment by verekia** [comment]
You are likely missing the import plugin for Babel (via "latest" preset) or the eslint import plugin. Make sure your package.json has everything: `https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/6-eslint/package.json`

**Comment by jfelipebc** [comment]
Thanks!!
