### ISSUE TITLE
 2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'

### ISSUE THREAD

**Issue by tribody** [verekia/js-stack-from-scratch#253]
### The error log displayed as follow:

$ yarn prod:start
```
yarn run v1.5.1
$ cross-env NODE_ENV=production pm2 start lib/server && pm2 logs
[PM2] Starting E:\workspaces\JsStackFromScratch\lib\server in fork_mode (1 insta
nce)
[PM2] Done.
┌────────┬──────┬─────────┬────┬─────┬──
──────┐
│ Name   │ mode │ status  │ ↺  │ cpu │ memory │
├────────┼──────┼─────────┼────┼─────┼──
──────┤
│ index  │ fork │ errored │ 15 │ 0%  │ 0 B    │
│ server │ fork │ online  │ 0  │ 0%  │ 0 B    │
└────────┴──────┴─────────┴────┴─────┴──
──────┘
 Use `pm2 show <id|name>` to get more details about an app
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lin
es option)
C:\Users\myname\.pm2\logs\server-out-2.log last 15 lines:
C:\Users\myname\.pm2\logs\server-error-2.log last 15 lines:
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3

2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [10524], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [31384], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [39776], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [17232], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [36604], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [42092], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [40872], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [30932], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [42224], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [25780], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [13428], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [42612], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [43124], exited with code [1] via
signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:server id:2
PM2        | App name:server id:2 online
2|server   | module.js:549
2|server   |     throw err;
2|server   |     ^
2|server   |
2|server   | Error: Cannot find module 'E:\workspaces\JsStackFromScratch\node_mo
dules\_pm2@2.10.1@pm2\lib\ProcessContainerFork.js'
2|server   |     at Function.Module._resolveFilename (module.js:547:15)
2|server   |     at Function.Module._load (module.js:474:25)
2|server   |     at Function.Module.runMain (module.js:693:10)
2|server   |     at startup (bootstrap_node.js:188:16)
2|server   |     at bootstrap_node.js:609:3
PM2        | App [server] with id [2] and pid [34608], exited with code [1] via
signal [SIGINT]
PM2        | Script E:\workspaces\JsStackFromScratch\lib\server had too many uns
table restarts (16). Stopped. "errored"
```

**Comment by austinpickett** [comment]
Did you run `yarn install`?

**Comment by verekia** [comment]
I'm going to assume that this isn't a problem anymore, as I clean up issues for the V3 of the tutorial. Cheers.
