### ISSUE TITLE
Does anyone know how to integrate uglify with this stack?

### ISSUE THREAD

**Issue by domino14** [verekia/js-stack-from-scratch#88]
Don't know how to get uglify working. I installed `yarn add --dev gulp-uglify babel-preset-es2015` and tried this:

```javascript
gulp.task('build-distribution', ['clean'], () =>
  gulp.src(paths.clientEntryPoint)
    .pipe(babel({
      presets: ['es2015'],
    }))
    .pipe(webpack(webpackConfig))
    .pipe(uglify())
    .pipe(gulp.dest(paths.distDir)));
```

And I get an error that looks like this:

```
$ gulp build-distribution
[21:54:04] Requiring external module babel-register
[21:54:04] Using gulpfile ~/coding/webolith/gulpfile.babel.js
[21:54:04] Starting 'clean'...
[21:54:04] Finished 'clean' after 11 ms
[21:54:04] Starting 'build-distribution'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: punc (:) (line: 1, col: 10, pos: 10)

Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2164:47)
    at eval (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
    at createError (/Users/cesar/coding/webolith/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Users/cesar/coding/webolith/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Users/cesar/coding/webolith/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Users/cesar/coding/webolith/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Stream.ondata (stream.js:31:26)
error Command failed with exit code 1.
```

**Comment by rahul-dutt-sharma** [comment]
you can add that as a plugin in webpack

On 12-Nov-2016, at 11:30, C?sar Del Solar <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't know how to get uglify working. I tried this:

gulp.task('build-distribution', ['clean'], () =>
  gulp.src(paths.clientEntryPoint)
    .pipe(babel({
      presets: ['es2015'],
    }))
    .pipe(webpack(webpackConfig))
    .pipe(uglify())
    .pipe(gulp.dest(paths.distDir)));

And I get an error that looks like this:

$ gulp build-distribution
[21:54:04] Requiring external module babel-register
[21:54:04] Using gulpfile ~/coding/webolith/gulpfile.babel.js
[21:54:04] Starting 'clean'...
[21:54:04] Finished 'clean' after 11 ms
[21:54:04] Starting 'build-distribution'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: punc (:) (line: 1, col: 10, pos: 10)

Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2164:47)
    at eval (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/Users/cesar/coding/webolith/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
    at createError (/Users/cesar/coding/webolith/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Users/cesar/coding/webolith/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Users/cesar/coding/webolith/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Users/cesar/coding/webolith/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/cesar/coding/webolith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Stream.ondata (stream.js:31:26)
error Command failed with exit code 1.


-

**Comment by verekia** [comment]
+1 for Webpack plugin. Check NODE_ENV to figure out if you should minify or not in your webpack config file though.

**Comment by domino14** [comment]
Thanks, Webpack worked great.
